server:
  port: 8081

spring:
  cache:
    type: caffeine

feign:
  client:
    config:
      keycloak:
        url: http://localhost:8080
        url-login: http://localhost:8080/realms/tpi_dh_gaston_campagno/protocol/openid-connect/token
        url-logout: http://localhost:8080/realms/tpi_dh_gaston_campagno/protocol/openid-connect/logout
        realm: tpi_dh_gaston_campagno
        client-id: ${KEYCLOAK_CLIENT_ID:admin-service} # Carga desde variables de entorno
        client-secret: ${KEYCLOAK_CLIENT_SECRET:082Rd79xNjUm9o8sSWms4tGRT7NUbugA} # Variables de entorno
        token-path: /realms/tpi_dh_gaston_campagno/protocol/openid-connect/token
