server:
  port: 8081

spring:
  cache:
    type: caffeine

feign:
  client:
    config:
      keycloak:
        url: http://localhost:8080
        realm: tpi_dh_gaston_campagno
        client-id: ${KEYCLOAK_CLIENT_ID:admin-service} # Carga desde variables de entorno
        client-secret: ${KEYCLOAK_CLIENT_SECRET:k0ffwii1RTQ37ISe58j3doQGMVICNPv2} # Variables de entorno
        token-path: /realms/tpi_dh_gaston_campagno/protocol/openid-connect/token
