spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: registry_login_logout
          uri: http://localhost:8080
          predicates:
            - Path=/api/**

server:
  port: 8084
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
